  export const genres: string[]  = [
    "Action",
    "Adventure",
    "Animation",
    "Biography (Biopic)",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Family",
    "Fantasy",
    "Historical",
    "Horror",
    "Musical",
    "Mystery",
    "Romance",
    "Science Fiction (Sci-Fi)",
    "Sports",
    "Thriller",
    "War",
    "Western",
    "Crime Thriller",
    "Psychological Thriller",
    "Survival",
    "Superhero",
    "Experimental"
]